"""clicks

Revision ID: 0c63aa3e951b
Revises: 1a29acd80ba3
Create Date: 2025-06-03 21:41:24.856318

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c63aa3e951b"
down_revision: Union[str, None] = "1a29acd80ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "click",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("url_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["url_uuid"], ["url.uuid"], name=op.f("fk_click_url_uuid_url"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_click")),
    )
    op.drop_column("url", "clicks_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("url", sa.Column("clicks_count", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table("click")
    # ### end Alembic commands ###
